# Generated by Django 2.1 on 2019-02-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.TextField(max_length=10000)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
